CASES = [
    {"id": "T01", "name": "integer_addition", "source": "printf(5 + 5);", "expected": "10"},
    {"id": "T02", "name": "integer_subtraction", "source": "printf(9 - 4);", "expected": "5"},
    {"id": "T03", "name": "integer_multiplication", "source": "printf(6 * 7);", "expected": "42"},
    {"id": "T04", "name": "integer_division", "source": "printf(20 / 4);", "expected": "5"},
    {"id": "T05", "name": "float_addition", "source": "printf(3.5 + 1.5);", "expected": "5.000000"},
    {"id": "T06", "name": "float_multiplication", "source": "printf(2.5 * 4.0);", "expected": "10.000000"},
    {"id": "T07", "name": "unary_negation", "source": "printf(-8);", "expected": "-8"},
    {"id": "T08", "name": "comparison_equal", "source": "printf(7 == 7);", "expected": "1"},
    {"id": "T09", "name": "comparison_not_equal", "source": "printf(7 != 9);", "expected": "1"},
    {"id": "T10", "name": "comparison_less_than", "source": "printf(3 < 5);", "expected": "1"},
    {"id": "T11", "name": "comparison_greater_than", "source": "printf(9 > 2);", "expected": "1"},
    {"id": "T12", "name": "logical_and", "source": "printf((1 < 2) && (3 > 1));", "expected": "1"},
    {"id": "T13", "name": "logical_or", "source": "printf((1 > 2) || (3 < 5));", "expected": "1"},
    {"id": "T14", "name": "logical_not", "source": "printf(!(2 == 3));", "expected": "1"},
    {"id": "T15", "name": "integer_variable", "source": "let x: int = 5; printf(x);", "expected": "5"},
    {"id": "T16", "name": "string_variable", "source": "let name: str = \"Alice\"; printf(name);", "expected": "Alice"},
    {"id": "T17", "name": "bool_variable", "source": "let ok: bool = true; printf(ok);", "expected": "1"},
    {"id": "T18", "name": "assignment", "source": "let x: int = 4; x = 7; printf(x);", "expected": "7"},
    {"id": "T19", "name": "string_concat_literal", "source": "printf(\"Hello\" + \" world\");", "expected": "Hello world"},
    {"id": "T20", "name": "string_concat_variable", "source": "let prefix: str = \"Hello\"; let suffix: str = \" world\"; printf(prefix + suffix);", "expected": "Hello world"},
    {"id": "T21", "name": "mixed_string_and_int_concat", "source": "let name: str = \"User\"; printf(\"Hello \" + name);", "expected": "Hello User"},
    {"id": "T22", "name": "single_if_true", "source": "if (5 > 3) { printf(\"yes\"); }", "expected": "yes"},
    {"id": "T23", "name": "single_if_false", "source": "if (3 > 5) { printf(\"yes\"); } else { printf(\"no\"); }", "expected": "no"},
    {"id": "T24", "name": "else_if_chain", "source": "let x: int = 2; if (x == 1) { printf(\"one\"); } else if (x == 2) { printf(\"two\"); } else { printf(\"other\"); }", "expected": "two"},
    {"id": "T25", "name": "nested_if", "source": "if (true) { if (false) { printf(\"bad\"); } else { printf(\"good\"); } }", "expected": "good"},
    {"id": "T26", "name": "while_loop", "source": "let i: int = 0; while (i < 3) { printf(i); i = i + 1; }", "expected": "0\n1\n2"},
    {"id": "T27", "name": "while_loop_with_condition", "source": "let count: int = 5; while (count > 0) { printf(count); count = count - 1; }", "expected": "5\n4\n3\n2\n1"},
    {"id": "T28", "name": "function_addition", "source": "func add(a: int, b: int): int { return a + b; } printf(add(2, 3));", "expected": "5"},
    {"id": "T29", "name": "function_two_params", "source": "func mul(a: int, b: int): int { return a * b; } printf(mul(4, 6));", "expected": "24"},
    {"id": "T30", "name": "function_no_params", "source": "func ping(): int { return 11; } printf(ping());", "expected": "11"},
    {"id": "T31", "name": "function_string_return", "source": "func greet(name: str): str { return \"Hi \" + name; } printf(greet(\"Sam\"));", "expected": "Hi Sam"},
    {"id": "T32", "name": "two_function_calls", "source": "func one(): int { return 1; } func two(): int { return 2; } printf(one()); printf(two());", "expected": "1\n2"},
    {"id": "T33", "name": "return_value_assignment", "source": "func get(): int { return 9; } let x: int = get(); printf(x);", "expected": "9"},
    {"id": "T34", "name": "comment_treatment", "source": "# comment\nprintf(1 + 1);\n# trailing comment", "expected": "2"},
    {"id": "T35", "name": "inline_comment", "source": "let x: int = 3; # comment\nprintf(x);", "expected": "3"},
    {"id": "T36", "name": "empty_lines_and_space", "source": "\n\n  let x: int = 7;\n\n  printf(x);\n\n", "expected": "7"},
    {"id": "T37", "name": "multiple_declarations", "source": "let a: int = 1; let b: int = 2; let c: int = 3; printf(a + b + c);", "expected": "6"},
    {"id": "T38", "name": "reassignment_in_loop", "source": "let i: int = 0; while (i < 2) { i = i + 1; printf(i); }", "expected": "1\n2"},
    {"id": "T39", "name": "comparison_string_equality", "source": "printf(\"hi\" == \"hi\");", "expected": "true"},
    {"id": "T40", "name": "comparison_string_less_than", "source": "printf(\"a\" < \"b\");", "expected": "true"},
    {"id": "T41", "name": "comparison_string_greater_than", "source": "printf(\"z\" > \"a\");", "expected": "true"},
    {"id": "T42", "name": "truthy_integer_check", "source": "if (5) { printf(\"nonzero\"); }", "expected": "nonzero"},
    {"id": "T43", "name": "truthy_string_check", "source": "if (\"hello\") { printf(\"present\"); }", "expected": "present"},
    {"id": "T44", "name": "falsey_zero_check", "source": "if (0) { printf(\"bad\"); } else { printf(\"zero\"); }", "expected": "zero"},
    {"id": "T45", "name": "nested_arithmetic", "source": "printf((2 + 3) * (5 - 1));", "expected": "20"},
    {"id": "T46", "name": "precedence_mixed", "source": "printf(10 + 2 * 3);", "expected": "16"},
    {"id": "T47", "name": "precedence_parentheses", "source": "printf((10 + 2) * 3);", "expected": "36"},
    {"id": "T48", "name": "two_prints_one_statement", "source": "printf(\"left\"); printf(\"right\");", "expected": "left\nright"},
    {"id": "T49", "name": "string_then_number", "source": "let msg: str = \"Result: \"; let value: int = 12; printf(msg + value);", "expected": "Result: 12"},
    {"id": "T50", "name": "loop_and_condition", "source": "let total: int = 0; let i: int = 0; while (i < 3) { total = total + i; if (i == 2) { printf(total); } i = i + 1; }", "expected": "2"},
    {"id": "T51", "name": "function_call_in_expression", "source": "func addone(x: int): int { return x + 1; } printf(addone(4) + 5);", "expected": "10"},
    {"id": "T52", "name": "multi_line_function", "source": "func sum(a: int, b: int): int {\n    let x: int = a + b;\n    return x;\n}\nprintf(sum(3, 4));", "expected": "7"},
    {"id": "T53", "name": "bool_logic_sequence", "source": "let a: bool = true; let b: bool = false; printf(a && b); printf(a || b); printf(!b);", "expected": "0\n1\n1"},
    {"id": "T54", "name": "variable_shadowing", "source": "let x: int = 1; let y: int = 2; x = x + y; printf(x);", "expected": "3"},
    {"id": "T55", "name": "combined_expression_output", "source": "let greeting: str = \"Hello\"; let target: str = \"World\"; printf(greeting + \" \" + target);", "expected": "Hello World"},
]
